// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func HandlersUserApi(db *gorm.DB) userAPI {
	mainUserRepository := newUserRepository(db)
	mainUserService := newUserService(mainUserRepository)
	mainUserAPI := newUserAPI(mainUserService)
	return mainUserAPI
}
